#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#  h2:
#    console:
#      enabled: true
jwt:
  issuer: ajufresh@gmail.com  #issuer : JWT 토큰의 발행자(일반적으로 이메일 또는 고유 식별자)입니다.
  secret_key: study-springboot  #secret_key : JWT 토큰 서명 및 확인에 사용되는 비밀 키입니다. 이 키가 안전하게 보관되고 노출되지 않도록 하세요.
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver  #드라이버 클래스 이름 : MySQL JDBC 드라이버의 클래스 이름입니다.
#    url: jdbc:mysql://192.168.0.165:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8  #url : MySQL 데이터베이스에 연결하기 위한 JDBC URL입니다. 서버 IP, 포트(3306), 데이터베이스 이름( test), 시간대 및 문자 인코딩을 지정합니다.
#    username: root
#    password: 1234



  server:
    error:
      path: /error  #error.path : 오류 처리에 사용되는 경로입니다.
    whitelabel:  #whitelabel.enabled : Spring Boot에서 제공하는 기본 오류 화이트라벨 페이지를 비활성화하므로 사용자 정의 오류 페이지를 사용할 수 있습니다.
      enabled: false

  thymeleaf:  #캐시 : 개발 중에 서버를 다시 시작하지 않고도 템플릿의 변경 사항을 즉시 반영하는 데 유용한 Thymeleaf 캐시를 비활성화합니다.
    cache: false



# 타임리프 헤더푸터 yaml/yml 파일
thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  enabled: true


